# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 18:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 4, 5, 18, 4, 59, 626564, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
